/*
 * This file is generated by jOOQ.
 */
package com.gemini.DummyScript.entity.demo;


import com.gemini.DummyScript.entity.demo.tables.Author;
import com.gemini.DummyScript.entity.demo.tables.Book;
import com.gemini.DummyScript.entity.demo.tables.Language;


/**
 * Convenience access to all tables in DEMO.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DEMO.AUTHOR</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>DEMO.BOOK</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>DEMO.LANGUAGE</code>.
     */
    public static final Language LANGUAGE = Language.LANGUAGE;
}
